printer_ips:
  - 192.168.1.100
  - 192.168.1.101
  # Add more printer IPs as needed

printer_users:
  192.168.1.100: UserA
  192.168.1.101: UserB
  # Assign user names to printer IPs

required_columns:
  - Date
  - PageCount
  - Status
  # Define required columns in the report

smtp_info:
  from_address: your_email@example.com
  to_addresses:
    - recipient1@example.com
    - recipient2@example.com
  host: smtp.example.com
  port: 587
  user: your_email@example.com
  password: your_email_password
  # SMTP email configuration

report_schedule:
  day_of_month: 20
  hour: 23
  minute: 59
  # Schedule for report generation
